# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      map_converter|map_converter_builder:
        enabled: True
        options:
          input: '^{{}}.dart'
          output: '{{}}_map_converter.dart'

builders:
  map_converter_builder:
    import: 'package:map_converter/builder.dart'
    builder_factories: ['mapConverterBuilder']
    build_extensions:
      see_option_input:
        - see_option_output
    build_to: source
    auto_apply: dependents


    # - lib/data/{{}}_map_converter.dart