name: map_converter
description: A builder that generates classes to convert objects to key-value maps and vise versa (e.g. for JSON and YAML conversions or key-value storage libraries).
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^5.12.0
  build: ^2.3.1
  collection: ^1.16.0
  dart_code: ^0.1.8
  json_annotation: ^4.8.1
  logging: ^1.0.2
  pub_semver: ^2.1.4
  recase: ^4.0.0
  yaml_writer: ^1.0.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.21.5
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

