name: map_converter
description: A builder that generates classes to convert objects to key-value maps and vise versa (e.g. for JSON and YAML conversions or key-value storage libraries).
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^7.2.0
  build: ^2.3.1
  collection: ^1.16.0
  dart_code: ^0.1.11
  logging: ^1.0.2
  pub_semver: ^2.1.4
  recase: ^4.0.0
  yaml_writer: ^2.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.5
  build_runner: ^2.3.3
  json_serializable: ^6.9.3
  shouldly: ^0.5.0+1
  json_annotation: ^4.9.0

