import '../../../example/lib/polymorphism/polymorphism.dart' as i1;
import '../../../example/lib/polymorphism/polymorphism.mapper.dart' as i2;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/polymorphism/polymorphism.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class AnimalMapper {
  const AnimalMapper();
  i1.Animal fromMap(Map<String, dynamic> map) {
    if (map['_type'] == 'Dog') {
      return const i2.DogMapper().fromMap(map);
    } else if (map['_type'] == 'Cat') {
      return const i2.CatMapper().fromMap(map);
    } else if (map['_type'] == 'Bird') {
      return const i2.BirdMapper().fromMap(map);
    } else {
      throw Exception('Unsupported map: $map');
    }
  }

  Map<String, dynamic> toMap(i1.Animal animal) => switch (animal.runtimeType) {
    i1.Dog => const i2.DogMapper().toMap(animal as i1.Dog),
    i1.Cat => const i2.CatMapper().toMap(animal as i1.Cat),
    i1.Bird => const i2.BirdMapper().toMap(animal as i1.Bird),
    _ => throw Exception('Unsupported type: ${animal.runtimeType}'),
  };
}

class DogMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Dog',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.dart',
    'mapperClassName': 'DogMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.mapper.dart',
    'fields': [
      {
        'name': 'name',
        'mapKey': 'name',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'barkVolume',
        'mapKey': 'barkVolume',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const DogMapper();
  i1.Dog fromMap(Map<String, dynamic> dogMap) => i1.Dog(
    name: dogMap['name'] as String,
    barkVolume: (dogMap['barkVolume'] as num).toInt(),
  );
  Map<String, dynamic> toMap(i1.Dog dog) => {
    '_type': 'Dog',
    'name': dog.name,
    'barkVolume': dog.barkVolume,
  };
}

class CatMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Cat',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.dart',
    'mapperClassName': 'CatMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.mapper.dart',
    'fields': [
      {
        'name': 'name',
        'mapKey': 'name',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'livesLeft',
        'mapKey': 'livesLeft',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const CatMapper();
  i1.Cat fromMap(Map<String, dynamic> catMap) => i1.Cat(
    name: catMap['name'] as String,
    livesLeft: (catMap['livesLeft'] as num).toInt(),
  );
  Map<String, dynamic> toMap(i1.Cat cat) => {
    '_type': 'Cat',
    'name': cat.name,
    'livesLeft': cat.livesLeft,
  };
}

class BirdMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Bird',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.dart',
    'mapperClassName': 'BirdMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.mapper.dart',
    'fields': [
      {
        'name': 'name',
        'mapKey': 'name',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'wingSpan',
        'mapKey': 'wingSpan',
        'description': '',
        'presence': 'required',
        'type': 'double',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const BirdMapper();
  i1.Bird fromMap(Map<String, dynamic> birdMap) => i1.Bird(
    name: birdMap['name'] as String,
    wingSpan: (birdMap['wingSpan'] as num).toDouble(),
  );
  Map<String, dynamic> toMap(i1.Bird bird) => {
    '_type': 'Bird',
    'name': bird.name,
    'wingSpan': bird.wingSpan,
  };
}

class PetClinicMapper {
  final Map<String, dynamic> schema = const {
    'className': 'PetClinic',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.dart',
    'mapperClassName': 'PetClinicMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/polymorphism/polymorphism.mapper.dart',
    'fields': [
      {
        'name': 'animals',
        'mapKey': 'animals',
        'description': '',
        'presence': 'required',
        'type': 'List<Animal>',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const PetClinicMapper();
  i1.PetClinic fromMap(Map<String, dynamic> petClinicMap) => i1.PetClinic(
    petClinicMap['animals']
        .map(
          (listElement) => const i2.AnimalMapper().fromMap(
            listElement as Map<String, dynamic>,
          ),
        )
        .toList()
        .cast<i1.Animal>(),
  );
  Map<String, dynamic> toMap(i1.PetClinic petClinic) => {
    'animals': petClinic.animals
        .map(
          (i1.Animal listElement) => const i2.AnimalMapper().toMap(listElement),
        )
        .toList(),
  };
}
