import 'package:map_converter/domain/example.dart' as _i1;
import 'package:map_converter/data/person/person_map_converter.dart' as _i2;
import 'package:map_converter/data/example_map_converter.dart' as _i3;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// On: 2022-08-23 09:46:53.847308
/// From: /map_converter/lib/domain/example.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
Map<String, dynamic> exampleToMap(_i1.Example example) => {
      'myString': example.myString,
      'myNullableString': example.myNullableString,
      'myNum': example.myNum,
      'myNullableNum': example.myNullableNum,
      'myInt': example.myInt,
      'myNullableInt': example.myNullableInt,
      'myDouble': example.myDouble,
      'myNullableDouble': example.myNullableDouble,
      'myBool': example.myBool,
      'myNullableBool': example.myNullableBool,
      'myEnum': example.myEnum.name,
      'myNullableEnum': example.myNullableEnum?.name,
      'myUri': example.myUri.toString(),
      'myNullableUri': example.myNullableUri?.toString(),
      'myBigInt': example.myBigInt.toString(),
      'myNullableBigInt': example.myNullableBigInt?.toString(),
      'myDateTime': example.myDateTime.toIso8601String(),
      'myNullableDateTime': example.myNullableDateTime?.toIso8601String(),
      'myDuration': example.myDuration.inMicroseconds,
      'myNullableDuration': example.myNullableDuration?.inMicroseconds,
      'myPerson': _i2.personToMap(example.myPerson),
      'myNullablePerson': example.myNullablePerson == null
          ? null
          : _i2.personToMap(example.myNullablePerson!),
      'myExample': _i3.exampleToMap(example.myExample),
      'myNullableExample': example.myNullableExample == null
          ? null
          : _i3.exampleToMap(example.myNullableExample!)
    };
