import '../../../example/lib/generate_option/generate_option.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/generate_option/generate_option.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ToMapExampleMapper {
  const ToMapExampleMapper();
  Map<String, dynamic> toMap(i1.ToMapExample toMapExample) => {
        'email': toMapExample.email,
        'phoneNumber': toMapExample.phoneNumber,
      };
}

class FromMapExampleMapper {
  const FromMapExampleMapper();
  i1.FromMapExample fromMap(Map<String, dynamic> fromMapExampleMap) =>
      i1.FromMapExample(
        fromMapExampleMap['email'] as String,
        (fromMapExampleMap['phoneNumber'] as num).toInt(),
      );
}

class SchemaExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'SchemaExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/generate_option/generate_option.dart',
    'mapperClassName': 'SchemaExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/generate_option/generate_option.mapper.dart',
    'fields': [
      {
        'name': 'email',
        'mapKey': 'email',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'phoneNumber',
        'mapKey': 'phoneNumber',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const SchemaExampleMapper();
}

class MapAndSchemaExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'MapAndSchemaExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/generate_option/generate_option.dart',
    'mapperClassName': 'MapAndSchemaExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/generate_option/generate_option.mapper.dart',
    'fields': [
      {
        'name': 'email',
        'mapKey': 'email',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'phoneNumber',
        'mapKey': 'phoneNumber',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const MapAndSchemaExampleMapper();
  Map<String, dynamic> toMap(i1.MapAndSchemaExample mapAndSchemaExample) => {
        'email': mapAndSchemaExample.email,
        'phoneNumber': mapAndSchemaExample.phoneNumber,
      };
}

class AllExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'AllExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/generate_option/generate_option.dart',
    'mapperClassName': 'AllExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/generate_option/generate_option.mapper.dart',
    'fields': [
      {
        'name': 'email',
        'mapKey': 'email',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'phoneNumber',
        'mapKey': 'phoneNumber',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const AllExampleMapper();
  i1.AllExample fromMap(Map<String, dynamic> allExampleMap) => i1.AllExample(
        allExampleMap['email'] as String,
        (allExampleMap['phoneNumber'] as num).toInt(),
      );
  Map<String, dynamic> toMap(i1.AllExample allExample) => {
        'email': allExample.email,
        'phoneNumber': allExample.phoneNumber,
      };
}
