import '../../example/alias/alias.domain.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// From: asset:map_converter/example/alias/alias.domain.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
Map<String, dynamic> aliasExampleToMap(i1.AliasExample aliasExample) => {
      'emailAddress': aliasExample.email,
      'contactNumber': aliasExample.phoneNumber,
      'name': aliasExample.name
    };
i1.AliasExample mapToAliasExample(Map<String, dynamic> aliasExampleMap) =>
    i1.AliasExample(
        name: aliasExampleMap['name'] as String,
        email: aliasExampleMap['emailAddress'] as String,
        phoneNumber: aliasExampleMap['contactNumber'] as int);
