import '../../../example/lib/type/bigint.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/bigint.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/bigint.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/bigint.mapper.dart',
    'fields': [
      {
        'name': 'myBigInt',
        'mapKey': 'myBigInt',
        'description': '',
        'presence': 'required',
        'type': 'BigInt',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'myNullableBigInt',
        'mapKey': 'myNullableBigInt',
        'description': '',
        'presence': 'optional',
        'type': 'BigInt?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myBigInt = BigInt.parse(exampleMap['myBigInt'] as String)
    ..myNullableBigInt = exampleMap['myNullableBigInt'] == null
        ? null
        : BigInt.parse(exampleMap['myNullableBigInt'] as String);
  Map<String, dynamic> toMap(i1.Example example) => {
        'myBigInt': example.myBigInt.toString(),
        'myNullableBigInt': example.myNullableBigInt?.toString(),
      };
}
