import '../../../example/lib/type/bool.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/bool.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/bool.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/bool.mapper.dart',
    'fields': [
      {
        'name': 'myBool',
        'mapKey': 'myBool',
        'description': '',
        'presence': 'required',
        'type': 'bool',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'myNullableBool',
        'mapKey': 'myNullableBool',
        'description': '',
        'presence': 'optional',
        'type': 'bool?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myBool = exampleMap['myBool'] as bool
    ..myNullableBool = exampleMap['myNullableBool'] as bool?;
  Map<String, dynamic> toMap(i1.Example example) => {
        'myBool': example.myBool,
        'myNullableBool': example.myNullableBool,
      };
}
