import '../../../example/lib/type/double.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/double.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/double.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/double.mapper.dart',
    'fields': [
      {
        'name': 'myDouble',
        'mapKey': 'myDouble',
        'description': '',
        'presence': 'required',
        'type': 'double',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'myNullableDouble',
        'mapKey': 'myNullableDouble',
        'description': '',
        'presence': 'optional',
        'type': 'double?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myDouble = (exampleMap['myDouble'] as num).toDouble()
    ..myNullableDouble = (exampleMap['myNullableDouble'] as num?)?.toDouble();
  Map<String, dynamic> toMap(i1.Example example) => {
        'myDouble': example.myDouble,
        'myNullableDouble': example.myNullableDouble,
      };
}
