import '../../../example/lib/type/double.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/double.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
i1.Example mapToExample(Map<String, dynamic> exampleMap) => i1.Example()
  ..myDouble = (exampleMap['myDouble'] as num).toDouble()
  ..myNullableDouble = (exampleMap['myNullableDouble'] as num?)?.toDouble();
Map<String, dynamic> exampleToMap(i1.Example example) => {
      'myDouble': example.myDouble,
      'myNullableDouble': example.myNullableDouble,
    };
