import '../../../example/lib/type/enum.dart' as i1;
import '../../../example/lib/person/person.dart' as i2;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/enum.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
i1.Example mapToExample(Map<String, dynamic> exampleMap) => i1.Example()
  ..myEnum = i2.Gender.values.firstWhere(
    (enumValue) => enumValue.name == exampleMap['myEnum'],
  )
  ..myNullableEnum = exampleMap['myNullableEnum'] == null
      ? null
      : i2.Gender.values.firstWhere(
          (enumValue) => enumValue.name == exampleMap['myNullableEnum'],
        );
Map<String, dynamic> exampleToMap(i1.Example example) => {
      'myEnum': example.myEnum.name,
      'myNullableEnum': example.myNullableEnum?.name,
    };
