import '../../../example/lib/type/enum.dart' as i1;
import '../../../example/lib/person/person.dart' as i2;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/enum.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/enum.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/enum.mapper.dart',
    'fields': [
      {
        'name': 'myEnum',
        'mapKey': 'myEnum',
        'description': '',
        'presence': 'required',
        'type': 'Gender',
        'typeLibraryUri': 'asset:map_converter/example/lib/person/person.dart',
      },
      {
        'name': 'myNullableEnum',
        'mapKey': 'myNullableEnum',
        'description': '',
        'presence': 'optional',
        'type': 'Gender?',
        'typeLibraryUri': 'asset:map_converter/example/lib/person/person.dart',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myEnum = i2.Gender.values.firstWhere(
      (enumValue) => enumValue.name == exampleMap['myEnum'],
    )
    ..myNullableEnum = exampleMap['myNullableEnum'] == null
        ? null
        : i2.Gender.values.firstWhere(
            (enumValue) => enumValue.name == exampleMap['myNullableEnum'],
          );
  Map<String, dynamic> toMap(i1.Example example) => {
        'myEnum': example.myEnum.name,
        'myNullableEnum': example.myNullableEnum?.name,
      };
}
