import '../../../example/lib/type/int.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/int.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/int.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/int.mapper.dart',
    'fields': [
      {
        'name': 'myInt',
        'mapKey': 'myInt',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'myNullableInt',
        'mapKey': 'myNullableInt',
        'description': '',
        'presence': 'optional',
        'type': 'int?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myInt = (exampleMap['myInt'] as num).toInt()
    ..myNullableInt = (exampleMap['myNullableInt'] as num?)?.toInt();
  Map<String, dynamic> toMap(i1.Example example) => {
        'myInt': example.myInt,
        'myNullableInt': example.myNullableInt,
      };
}
