import '../../../example/lib/type/int.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/int.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
i1.Example mapToExample(Map<String, dynamic> exampleMap) => i1.Example()
  ..myInt = (exampleMap['myInt'] as num).toInt()
  ..myNullableInt = (exampleMap['myNullableInt'] as num?)?.toInt();
Map<String, dynamic> exampleToMap(i1.Example example) => {
      'myInt': example.myInt,
      'myNullableInt': example.myNullableInt,
    };
