import '../../../example/lib/type/iterable.dart' as i1;
import '../../../example/lib/person/person.dart' as i2;
import '../../../example/lib/person/person.mapper.dart' as i3;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/iterable.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/iterable.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/iterable.mapper.dart',
    'fields': [
      {
        'name': 'iterableOfBool',
        'mapKey': 'iterableOfBool',
        'description': '',
        'presence': 'required',
        'type': 'Iterable',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'iterableOfGender',
        'mapKey': 'iterableOfGender',
        'description': '',
        'presence': 'required',
        'type': 'Iterable',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'iterableOfPerson',
        'mapKey': 'iterableOfPerson',
        'description': '',
        'presence': 'required',
        'type': 'Iterable',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'iterableOfNullableInt',
        'mapKey': 'iterableOfNullableInt',
        'description': '',
        'presence': 'required',
        'type': 'Iterable',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableIterableOfDouble',
        'mapKey': 'nullableIterableOfDouble',
        'description': '',
        'presence': 'optional',
        'type': 'Iterable',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableIterableOfNullableStrings',
        'mapKey': 'nullableIterableOfNullableStrings',
        'description': '',
        'presence': 'optional',
        'type': 'Iterable',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..iterableOfBool = exampleMap['iterableOfBool']
        .map((element) => element as bool)
        .toList()
        .cast<bool>()
    ..iterableOfGender = exampleMap['iterableOfGender']
        .map(
          (element) => i2.Gender.values.firstWhere(
            (enumValue) => enumValue.name == element,
          ),
        )
        .toList()
        .cast<i2.Gender>()
    ..iterableOfPerson = exampleMap['iterableOfPerson']
        .map(
          (element) =>
              const i3.PersonMapper().fromMap(element as Map<String, dynamic>),
        )
        .toList()
        .cast<i2.Person>()
    ..iterableOfNullableInt = exampleMap['iterableOfNullableInt']
        .map((element) => (element as num?)?.toInt())
        .toList()
        .cast<int?>()
    ..nullableIterableOfDouble = exampleMap['nullableIterableOfDouble']
        ?.map((element) => (element as num).toDouble())
        .toList()
        .cast<double>()
    ..nullableIterableOfNullableStrings =
        exampleMap['nullableIterableOfNullableStrings']
            ?.map((element) => element as String?)
            .toList()
            .cast<String?>();
  Map<String, dynamic> toMap(i1.Example example) => {
        'iterableOfBool': example.iterableOfBool,
        'iterableOfGender': example.iterableOfGender
            .map((i2.Gender element) => element.name)
            .toList(),
        'iterableOfPerson': example.iterableOfPerson
            .map((i2.Person element) => const i3.PersonMapper().toMap(element))
            .toList(),
        'iterableOfNullableInt': example.iterableOfNullableInt,
        'nullableIterableOfDouble': example.nullableIterableOfDouble,
        'nullableIterableOfNullableStrings':
            example.nullableIterableOfNullableStrings,
      };
}
