import '../../../example/lib/type/list.dart' as i1;
import '../../../example/lib/person/person.dart' as i2;
import '../../../example/lib/person/person.mapper.dart' as i3;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/list.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/list.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/list.mapper.dart',
    'fields': [
      {
        'name': 'boolList',
        'mapKey': 'boolList',
        'description': '',
        'presence': 'required',
        'type': 'List<bool>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'boolListWithNullableBools',
        'mapKey': 'boolListWithNullableBools',
        'description': '',
        'presence': 'required',
        'type': 'List<bool?>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableBoolList',
        'mapKey': 'nullableBoolList',
        'description': '',
        'presence': 'optional',
        'type': 'List<bool>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableBoolListWithNullableBools',
        'mapKey': 'nullableBoolListWithNullableBools',
        'description': '',
        'presence': 'optional',
        'type': 'List<bool?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'numList',
        'mapKey': 'numList',
        'description': '',
        'presence': 'required',
        'type': 'List<num>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableNumList',
        'mapKey': 'nullableNumList',
        'description': '',
        'presence': 'optional',
        'type': 'List<num?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'intList',
        'mapKey': 'intList',
        'description': '',
        'presence': 'required',
        'type': 'List<int>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableIntList',
        'mapKey': 'nullableIntList',
        'description': '',
        'presence': 'optional',
        'type': 'List<int?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'doubleList',
        'mapKey': 'doubleList',
        'description': '',
        'presence': 'required',
        'type': 'List<double>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableDoubleList',
        'mapKey': 'nullableDoubleList',
        'description': '',
        'presence': 'optional',
        'type': 'List<double?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'stringList',
        'mapKey': 'stringList',
        'description': '',
        'presence': 'required',
        'type': 'List<String>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableStringList',
        'mapKey': 'nullableStringList',
        'description': '',
        'presence': 'optional',
        'type': 'List<String?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'uriList',
        'mapKey': 'uriList',
        'description': '',
        'presence': 'required',
        'type': 'List<Uri>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableUriList',
        'mapKey': 'nullableUriList',
        'description': '',
        'presence': 'optional',
        'type': 'List<Uri?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'bigIntList',
        'mapKey': 'bigIntList',
        'description': '',
        'presence': 'required',
        'type': 'List<BigInt>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableBigIntList',
        'mapKey': 'nullableBigIntList',
        'description': '',
        'presence': 'optional',
        'type': 'List<BigInt?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'dateTimeList',
        'mapKey': 'dateTimeList',
        'description': '',
        'presence': 'required',
        'type': 'List<DateTime>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableDateTimeList',
        'mapKey': 'nullableDateTimeList',
        'description': '',
        'presence': 'optional',
        'type': 'List<DateTime?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'durationList',
        'mapKey': 'durationList',
        'description': '',
        'presence': 'required',
        'type': 'List<Duration>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableDurationList',
        'mapKey': 'nullableDurationList',
        'description': '',
        'presence': 'optional',
        'type': 'List<Duration?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'genderList',
        'mapKey': 'genderList',
        'description': '',
        'presence': 'required',
        'type': 'List<Gender>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableGenderList',
        'mapKey': 'nullableGenderList',
        'description': '',
        'presence': 'optional',
        'type': 'List<Gender?>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'personList',
        'mapKey': 'personList',
        'description': '',
        'presence': 'required',
        'type': 'List<Person>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullablePersonList',
        'mapKey': 'nullablePersonList',
        'description': '',
        'presence': 'optional',
        'type': 'List<Person?>?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..boolList = exampleMap['boolList']
        .map((listElement) => listElement as bool)
        .toList()
        .cast<bool>()
    ..boolListWithNullableBools = exampleMap['boolListWithNullableBools']
        .map((listElement) => listElement as bool?)
        .toList()
        .cast<bool?>()
    ..nullableBoolList = exampleMap['nullableBoolList']
        ?.map((listElement) => listElement as bool)
        .toList()
        .cast<bool>()
    ..nullableBoolListWithNullableBools =
        exampleMap['nullableBoolListWithNullableBools']
            ?.map((listElement) => listElement as bool?)
            .toList()
            .cast<bool?>()
    ..numList = exampleMap['numList']
        .map((listElement) => listElement as num)
        .toList()
        .cast<num>()
    ..nullableNumList = exampleMap['nullableNumList']
        ?.map((listElement) => listElement as num?)
        .toList()
        .cast<num?>()
    ..intList = exampleMap['intList']
        .map((listElement) => (listElement as num).toInt())
        .toList()
        .cast<int>()
    ..nullableIntList = exampleMap['nullableIntList']
        ?.map((listElement) => (listElement as num?)?.toInt())
        .toList()
        .cast<int?>()
    ..doubleList = exampleMap['doubleList']
        .map((listElement) => (listElement as num).toDouble())
        .toList()
        .cast<double>()
    ..nullableDoubleList = exampleMap['nullableDoubleList']
        ?.map((listElement) => (listElement as num?)?.toDouble())
        .toList()
        .cast<double?>()
    ..stringList = exampleMap['stringList']
        .map((listElement) => listElement as String)
        .toList()
        .cast<String>()
    ..nullableStringList = exampleMap['nullableStringList']
        ?.map((listElement) => listElement as String?)
        .toList()
        .cast<String?>()
    ..uriList = exampleMap['uriList']
        .map((listElement) => Uri.parse(listElement as String))
        .toList()
        .cast<Uri>()
    ..nullableUriList = exampleMap['nullableUriList']
        ?.map(
          (listElement) =>
              listElement == null ? null : Uri.parse(listElement as String),
        )
        .toList()
        .cast<Uri?>()
    ..bigIntList = exampleMap['bigIntList']
        .map((listElement) => BigInt.parse(listElement as String))
        .toList()
        .cast<BigInt>()
    ..nullableBigIntList = exampleMap['nullableBigIntList']
        ?.map(
          (listElement) =>
              listElement == null ? null : BigInt.parse(listElement as String),
        )
        .toList()
        .cast<BigInt?>()
    ..dateTimeList = exampleMap['dateTimeList']
        .map((listElement) => DateTime.parse(listElement as String))
        .toList()
        .cast<DateTime>()
    ..nullableDateTimeList = exampleMap['nullableDateTimeList']
        ?.map(
          (listElement) => listElement == null
              ? null
              : DateTime.parse(listElement as String),
        )
        .toList()
        .cast<DateTime?>()
    ..durationList = exampleMap['durationList']
        .map((listElement) => Duration(microseconds: listElement as int))
        .toList()
        .cast<Duration>()
    ..nullableDurationList = exampleMap['nullableDurationList']
        ?.map(
          (listElement) => listElement == null
              ? null
              : Duration(microseconds: listElement as int),
        )
        .toList()
        .cast<Duration?>()
    ..genderList = exampleMap['genderList']
        .map(
          (listElement) => i2.Gender.values.firstWhere(
            (enumValue) => enumValue.name == listElement,
          ),
        )
        .toList()
        .cast<i2.Gender>()
    ..nullableGenderList = exampleMap['nullableGenderList']
        ?.map(
          (listElement) => listElement == null
              ? null
              : i2.Gender.values.firstWhere(
                  (enumValue) => enumValue.name == listElement,
                ),
        )
        .toList()
        .cast<i2.Gender?>()
    ..personList = exampleMap['personList']
        .map(
          (listElement) => const i3.PersonMapper().fromMap(
            listElement as Map<String, dynamic>,
          ),
        )
        .toList()
        .cast<i2.Person>()
    ..nullablePersonList = exampleMap['nullablePersonList']
        ?.map(
          (listElement) => listElement == null
              ? null
              : const i3.PersonMapper().fromMap(
                  listElement as Map<String, dynamic>,
                ),
        )
        .toList()
        .cast<i2.Person?>();
  Map<String, dynamic> toMap(i1.Example example) => {
        'boolList': example.boolList,
        'boolListWithNullableBools': example.boolListWithNullableBools,
        'nullableBoolList': example.nullableBoolList,
        'nullableBoolListWithNullableBools':
            example.nullableBoolListWithNullableBools,
        'numList': example.numList,
        'nullableNumList': example.nullableNumList,
        'intList': example.intList,
        'nullableIntList': example.nullableIntList,
        'doubleList': example.doubleList,
        'nullableDoubleList': example.nullableDoubleList,
        'stringList': example.stringList,
        'nullableStringList': example.nullableStringList,
        'uriList': example.uriList
            .map((Uri listElement) => listElement.toString())
            .toList(),
        'nullableUriList': example.nullableUriList
            ?.map((Uri? listElement) => listElement?.toString())
            .toList(),
        'bigIntList': example.bigIntList
            .map((BigInt listElement) => listElement.toString())
            .toList(),
        'nullableBigIntList': example.nullableBigIntList
            ?.map((BigInt? listElement) => listElement?.toString())
            .toList(),
        'dateTimeList': example.dateTimeList
            .map((DateTime listElement) => listElement.toIso8601String())
            .toList(),
        'nullableDateTimeList': example.nullableDateTimeList
            ?.map((DateTime? listElement) => listElement?.toIso8601String())
            .toList(),
        'durationList': example.durationList
            .map((Duration listElement) => listElement.inMicroseconds)
            .toList(),
        'nullableDurationList': example.nullableDurationList
            ?.map((Duration? listElement) => listElement?.inMicroseconds)
            .toList(),
        'genderList': example.genderList
            .map((i2.Gender listElement) => listElement.name)
            .toList(),
        'nullableGenderList': example.nullableGenderList
            ?.map((i2.Gender? listElement) => listElement?.name)
            .toList(),
        'personList': example.personList
            .map(
              (i2.Person listElement) =>
                  const i3.PersonMapper().toMap(listElement),
            )
            .toList(),
        'nullablePersonList': example.nullablePersonList
            ?.map(
              (i2.Person? listElement) => listElement == null
                  ? null
                  : const i3.PersonMapper().toMap(listElement),
            )
            .toList(),
      };
}
