import '../../../example/lib/type/map.dart' as i1;
import '../../../example/lib/person/person.mapper.dart' as i2;
import '../../../example/lib/person/person.dart' as i3;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/map.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/map.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/map.mapper.dart',
    'fields': [
      {
        'name': 'mapWithPrimitiveKeyAndPrimitiveValue',
        'mapKey': 'mapWithPrimitiveKeyAndPrimitiveValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableMapWithPrimitiveKeyAndPrimitiveValue',
        'mapKey': 'nullableMapWithPrimitiveKeyAndPrimitiveValue',
        'description': '',
        'presence': 'optional',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndPrimitiveNullableValue',
        'mapKey': 'mapWithPrimitiveKeyAndPrimitiveNullableValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndComplexValue',
        'mapKey': 'mapWithPrimitiveKeyAndComplexValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndComplexNullableValue',
        'mapKey': 'mapWithPrimitiveKeyAndComplexNullableValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndListValue',
        'mapKey': 'mapWithPrimitiveKeyAndListValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndNullableListValue',
        'mapKey': 'mapWithPrimitiveKeyAndNullableListValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndMapValue',
        'mapKey': 'mapWithPrimitiveKeyAndMapValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'mapWithPrimitiveKeyAndNullableMapValue',
        'mapKey': 'mapWithPrimitiveKeyAndNullableMapValue',
        'description': '',
        'presence': 'required',
        'type': 'Map',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..mapWithPrimitiveKeyAndPrimitiveValue =
        (exampleMap['mapWithPrimitiveKeyAndPrimitiveValue'] as Map).map(
      (k, v) => MapEntry(k, (v as num).toInt()),
    )
    ..nullableMapWithPrimitiveKeyAndPrimitiveValue =
        (exampleMap['nullableMapWithPrimitiveKeyAndPrimitiveValue'] as Map?)
            ?.map((k, v) => MapEntry((k as num).toInt(), v as bool))
    ..mapWithPrimitiveKeyAndPrimitiveNullableValue =
        (exampleMap['mapWithPrimitiveKeyAndPrimitiveNullableValue'] as Map).map(
      (k, v) => MapEntry((k as num).toDouble(), v as String?),
    )
    ..mapWithPrimitiveKeyAndComplexValue =
        (exampleMap['mapWithPrimitiveKeyAndComplexValue'] as Map).map(
      (k, v) => MapEntry(
        (k as num).toInt(),
        const i2.PersonMapper().fromMap(v as Map<String, dynamic>),
      ),
    )
    ..mapWithPrimitiveKeyAndComplexNullableValue =
        (exampleMap['mapWithPrimitiveKeyAndComplexNullableValue'] as Map).map(
      (k, v) => MapEntry(
        (k as num).toInt(),
        v == null
            ? null
            : const i2.PersonMapper().fromMap(v as Map<String, dynamic>),
      ),
    )
    ..mapWithPrimitiveKeyAndListValue =
        (exampleMap['mapWithPrimitiveKeyAndListValue'] as Map).map(
      (k, v) => MapEntry(
        (k as num).toInt(),
        v
            .map(
              (listElement) => const i2.PersonMapper().fromMap(
                listElement as Map<String, dynamic>,
              ),
            )
            .toList()
            .cast<i3.Person>(),
      ),
    )
    ..mapWithPrimitiveKeyAndNullableListValue =
        (exampleMap['mapWithPrimitiveKeyAndNullableListValue'] as Map).map(
      (k, v) => MapEntry(
        (k as num).toInt(),
        v
            ?.map(
              (listElement) => i3.Gender.values.firstWhere(
                (enumValue) => enumValue.name == listElement,
              ),
            )
            .toList()
            .cast<i3.Gender>(),
      ),
    )
    ..mapWithPrimitiveKeyAndMapValue =
        (exampleMap['mapWithPrimitiveKeyAndMapValue'] as Map).map(
      (k, v) => MapEntry(
        (k as num).toInt(),
        (v as Map).map(
          (k, v) => MapEntry(
            (k as num).toInt(),
            v == null
                ? null
                : const i2.PersonMapper().fromMap(
                    v as Map<String, dynamic>,
                  ),
          ),
        ),
      ),
    )
    ..mapWithPrimitiveKeyAndNullableMapValue =
        (exampleMap['mapWithPrimitiveKeyAndNullableMapValue'] as Map).map(
      (k, v) => MapEntry(
        (k as num).toInt(),
        (v as Map?)?.map(
          (k, v) => MapEntry(
            (k as num).toInt(),
            i3.Gender.values.firstWhere((enumValue) => enumValue.name == v),
          ),
        ),
      ),
    );
  Map<String, dynamic> toMap(i1.Example example) => {
        'mapWithPrimitiveKeyAndPrimitiveValue':
            example.mapWithPrimitiveKeyAndPrimitiveValue,
        'nullableMapWithPrimitiveKeyAndPrimitiveValue':
            example.nullableMapWithPrimitiveKeyAndPrimitiveValue,
        'mapWithPrimitiveKeyAndPrimitiveNullableValue':
            example.mapWithPrimitiveKeyAndPrimitiveNullableValue,
        'mapWithPrimitiveKeyAndComplexValue': example
            .mapWithPrimitiveKeyAndComplexValue
            .map((k, v) => MapEntry(k, const i2.PersonMapper().toMap(v))),
        'mapWithPrimitiveKeyAndComplexNullableValue':
            example.mapWithPrimitiveKeyAndComplexNullableValue.map(
          (k, v) =>
              MapEntry(k, v == null ? null : const i2.PersonMapper().toMap(v)),
        ),
        'mapWithPrimitiveKeyAndListValue':
            example.mapWithPrimitiveKeyAndListValue.map(
          (k, v) => MapEntry(
            k,
            v
                .map(
                  (i3.Person listElement) =>
                      const i2.PersonMapper().toMap(listElement),
                )
                .toList(),
          ),
        ),
        'mapWithPrimitiveKeyAndNullableListValue':
            example.mapWithPrimitiveKeyAndNullableListValue.map(
          (k, v) => MapEntry(
            k,
            v?.map((i3.Gender listElement) => listElement.name).toList(),
          ),
        ),
        'mapWithPrimitiveKeyAndMapValue':
            example.mapWithPrimitiveKeyAndMapValue.map(
          (k, v) => MapEntry(
            k,
            v.map(
              (k, v) => MapEntry(
                k,
                v == null ? null : const i2.PersonMapper().toMap(v),
              ),
            ),
          ),
        ),
        'mapWithPrimitiveKeyAndNullableMapValue': example
            .mapWithPrimitiveKeyAndNullableMapValue
            .map((k, v) => MapEntry(k, v?.map((k, v) => MapEntry(k, v.name)))),
      };
}
