import '../../../example/lib/type/num.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/num.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myNum = exampleMap['myNum'] as num
    ..myNullableNum = exampleMap['myNullableNum'] as num?;
  Map<String, dynamic> toMap(i1.Example example) => {
        'myNum': example.myNum,
        'myNullableNum': example.myNullableNum,
      };
}
