import '../../../example/lib/type/object.dart' as i1;
import '../../../example/lib/person/person.mapper.dart' as i2;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/object.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/object.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/object.mapper.dart',
    'fields': [
      {
        'name': 'myPerson',
        'mapKey': 'myPerson',
        'description': '',
        'presence': 'required',
        'type': 'Person',
        'typeLibraryUri': 'asset:map_converter/example/lib/person/person.dart',
      },
      {
        'name': 'myNullablePerson',
        'mapKey': 'myNullablePerson',
        'description': '',
        'presence': 'optional',
        'type': 'Person?',
        'typeLibraryUri': 'asset:map_converter/example/lib/person/person.dart',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myPerson = const i2.PersonMapper().fromMap(
      exampleMap['myPerson'] as Map<String, dynamic>,
    )
    ..myNullablePerson = exampleMap['myNullablePerson'] == null
        ? null
        : const i2.PersonMapper().fromMap(
            exampleMap['myNullablePerson'] as Map<String, dynamic>,
          );
  Map<String, dynamic> toMap(i1.Example example) => {
        'myPerson': const i2.PersonMapper().toMap(example.myPerson),
        'myNullablePerson': example.myNullablePerson == null
            ? null
            : const i2.PersonMapper().toMap(example.myNullablePerson!),
      };
}
