import '../../../example/lib/type/set.dart' as i1;
import '../../../example/lib/person/person.dart' as i2;
import '../../../example/lib/person/person.mapper.dart' as i3;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/set.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/set.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/set.mapper.dart',
    'fields': [
      {
        'name': 'setOfBool',
        'mapKey': 'setOfBool',
        'description': '',
        'presence': 'required',
        'type': 'Set<bool>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'setOfGender',
        'mapKey': 'setOfGender',
        'description': '',
        'presence': 'required',
        'type': 'Set<Gender>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'setOfPerson',
        'mapKey': 'setOfPerson',
        'description': '',
        'presence': 'required',
        'type': 'Set<Person>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'setOfNullableInt',
        'mapKey': 'setOfNullableInt',
        'description': '',
        'presence': 'required',
        'type': 'Set<int?>',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableSetOfDouble',
        'mapKey': 'nullableSetOfDouble',
        'description': '',
        'presence': 'optional',
        'type': 'Set<double>?',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'nullableSetOfNullableStrings',
        'mapKey': 'nullableSetOfNullableStrings',
        'description': '',
        'presence': 'optional',
        'type': 'Set<String?>?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..setOfBool = exampleMap['setOfBool']
        .map((setElement) => setElement as bool)
        .toSet()
        .cast<bool>()
    ..setOfGender = exampleMap['setOfGender']
        .map(
          (setElement) => i2.Gender.values.firstWhere(
            (enumValue) => enumValue.name == setElement,
          ),
        )
        .toSet()
        .cast<i2.Gender>()
    ..setOfPerson = exampleMap['setOfPerson']
        .map(
          (setElement) => const i3.PersonMapper().fromMap(
            setElement as Map<String, dynamic>,
          ),
        )
        .toSet()
        .cast<i2.Person>()
    ..setOfNullableInt = exampleMap['setOfNullableInt']
        .map((setElement) => (setElement as num?)?.toInt())
        .toSet()
        .cast<int?>()
    ..nullableSetOfDouble = exampleMap['nullableSetOfDouble']
        ?.map((setElement) => (setElement as num).toDouble())
        .toSet()
        .cast<double>()
    ..nullableSetOfNullableStrings = exampleMap['nullableSetOfNullableStrings']
        ?.map((setElement) => setElement as String?)
        .toSet()
        .cast<String?>();
  Map<String, dynamic> toMap(i1.Example example) => {
        'setOfBool': example.setOfBool,
        'setOfGender': example.setOfGender
            .map((i2.Gender setElement) => setElement.name)
            .toSet(),
        'setOfPerson': example.setOfPerson
            .map(
              (i2.Person setElement) =>
                  const i3.PersonMapper().toMap(setElement),
            )
            .toSet(),
        'setOfNullableInt': example.setOfNullableInt,
        'nullableSetOfDouble': example.nullableSetOfDouble,
        'nullableSetOfNullableStrings': example.nullableSetOfNullableStrings,
      };
}
