import '../../../example/lib/type/string.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/string.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/string.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/string.mapper.dart',
    'fields': [
      {
        'name': 'myString',
        'mapKey': 'myString',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'myNullableString',
        'mapKey': 'myNullableString',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myString = exampleMap['myString'] as String
    ..myNullableString = exampleMap['myNullableString'] as String?;
  Map<String, dynamic> toMap(i1.Example example) => {
        'myString': example.myString,
        'myNullableString': example.myNullableString,
      };
}
