import '../../../example/lib/type/string.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/string.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
i1.Example mapToExample(Map<String, dynamic> exampleMap) => i1.Example()
  ..string = exampleMap['string'] as String
  ..nullableString = exampleMap['nullableString'] as String?;
Map<String, dynamic> exampleToMap(i1.Example example) => {
      'string': example.string,
      'nullableString': example.nullableString,
    };
