import '../../../example/lib/type/uri.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/type/uri.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/type/uri.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/type/uri.mapper.dart',
    'fields': [
      {
        'name': 'myUri',
        'mapKey': 'myUri',
        'description': '',
        'presence': 'required',
        'type': 'Uri',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'myNullableUri',
        'mapKey': 'myNullableUri',
        'description': '',
        'presence': 'optional',
        'type': 'Uri?',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example()
    ..myUri = Uri.parse(exampleMap['myUri'] as String)
    ..myNullableUri = exampleMap['myNullableUri'] == null
        ? null
        : Uri.parse(exampleMap['myNullableUri'] as String);
  Map<String, dynamic> toMap(i1.Example example) => {
        'myUri': example.myUri.toString(),
        'myNullableUri': example.myNullableUri?.toString(),
      };
}
