import '../../../example/lib/custom_converter/custom_converter.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/custom_converter/custom_converter.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
i1.Example mapToExample(Map<String, dynamic> exampleMap) =>
    i1.Example(i1.MyConverter().fromPrimitive(exampleMap['dateTime']));
Map<String, dynamic> exampleToMap(i1.Example example) => {
      'dateTime': i1.MyConverter().toPrimitive(example.dateTime),
    };
