import '../../example/custom_converter/custom_converter.domain.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// On: 2025-01-25 11:24:02.421835
/// From: asset:map_converter/example/custom_converter/custom_converter.domain.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
Map<String, dynamic> customMappingExampleToMap(
        i1.CustomMappingExample customMappingExample) =>
    {'duration': customMappingExample.duration.inMicroseconds};
i1.CustomMappingExample mapToCustomMappingExample(
        Map<String, dynamic> customMappingExampleMap) =>
    i1.CustomMappingExample(
        Duration(microseconds: customMappingExampleMap['duration'] as int));
