import '../../example/custom_converter/custom_converter.domain.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// From: asset:map_converter/example/custom_converter/custom_converter.domain.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
Map<String, dynamic> customMappingExampleToMap(
        i1.CustomMappingExample customMappingExample) =>
    {
      'dateTime':
          i1.MyCustomConverter().toPrimitive(customMappingExample.dateTime)
    };
i1.CustomMappingExample mapToCustomMappingExample(
        Map<String, dynamic> customMappingExampleMap) =>
    i1.CustomMappingExample(i1.MyCustomConverter()
        .fromPrimitive(customMappingExampleMap['dateTime']));
