import '../../example/ignore/ignore.domain.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// From: asset:map_converter/example/ignore/ignore.domain.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
Map<String, dynamic> ignoreExampleToMap(i1.IgnoreExample ignoreExample) =>
    {'keep': ignoreExample.keep};
i1.IgnoreExample mapToIgnoreExample(Map<String, dynamic> ignoreExampleMap) =>
    i1.IgnoreExample()..keep = ignoreExampleMap['keep'] as bool;
