import '../../example/type_example/type_example.domain.dart' as i1;
import '../../example/person/person_map_converter.data.dart' as i2;
import '../../example/type_example/type_example_map_converter.data.dart' as i3;
import '../../example/person/person.domain.dart' as i4;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// On: 2025-01-17 17:03:52.122917
/// From: asset:map_converter/example/type_example/type_example.domain.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
Map<String, dynamic> typeExampleToMap(i1.TypeExample typeExample) => {
      'myString': typeExample.myString,
      'myNullableString': typeExample.myNullableString,
      'myNum': typeExample.myNum,
      'myNullableNum': typeExample.myNullableNum,
      'myInt': typeExample.myInt,
      'myNullableInt': typeExample.myNullableInt,
      'myDouble': typeExample.myDouble,
      'myNullableDouble': typeExample.myNullableDouble,
      'myBool': typeExample.myBool,
      'myNullableBool': typeExample.myNullableBool,
      'myEnum': typeExample.myEnum.name,
      'myNullableEnum': typeExample.myNullableEnum?.name,
      'myUri': typeExample.myUri.toString(),
      'myNullableUri': typeExample.myNullableUri?.toString(),
      'myBigInt': typeExample.myBigInt.toString(),
      'myNullableBigInt': typeExample.myNullableBigInt?.toString(),
      'myDateTime': typeExample.myDateTime.toIso8601String(),
      'myNullableDateTime': typeExample.myNullableDateTime?.toIso8601String(),
      'myDuration': typeExample.myDuration.inMicroseconds,
      'myNullableDuration': typeExample.myNullableDuration?.inMicroseconds,
      'myPerson': i2.personToMap(typeExample.myPerson),
      'myNullablePerson': typeExample.myNullablePerson == null
          ? null
          : i2.personToMap(typeExample.myNullablePerson!),
      'myExample': i3.typeExampleToMap(typeExample.myExample),
      'myNullableExample': typeExample.myNullableExample == null
          ? null
          : i3.typeExampleToMap(typeExample.myNullableExample!),
      'myBoolList': typeExample.myBoolList,
      'myNullableBoolList': typeExample.myNullableBoolList,
      'myNumList': typeExample.myNumList,
      'myNullableNumList': typeExample.myNullableNumList,
      'myIntList': typeExample.myIntList,
      'myNullableIntList': typeExample.myNullableIntList,
      'myDoubleList': typeExample.myDoubleList,
      'myNullableDoubleList': typeExample.myNullableDoubleList,
      'myStringList': typeExample.myStringList,
      'myNullableStringList': typeExample.myNullableStringList,
      'myUriList': typeExample.myUriList
          .map((Uri listElement) => listElement.toString())
          .toList(),
      'myNullableUriList': typeExample.myNullableUriList
          ?.map((Uri? listElement) => listElement?.toString())
          .toList(),
      'myBigIntList': typeExample.myBigIntList
          .map((BigInt listElement) => listElement.toString())
          .toList(),
      'myNullableBigIntList': typeExample.myNullableBigIntList
          ?.map((BigInt? listElement) => listElement?.toString())
          .toList(),
      'myDateTimeList': typeExample.myDateTimeList
          .map((DateTime listElement) => listElement.toIso8601String())
          .toList(),
      'myNullableDateTimeList': typeExample.myNullableDateTimeList
          ?.map((DateTime? listElement) => listElement?.toIso8601String())
          .toList(),
      'myDurationList': typeExample.myDurationList
          .map((Duration listElement) => listElement.inMicroseconds)
          .toList(),
      'myNullableDurationList': typeExample.myNullableDurationList
          ?.map((Duration? listElement) => listElement?.inMicroseconds)
          .toList(),
      'myGenderList': typeExample.myGenderList
          .map((i4.Gender listElement) => listElement.name)
          .toList(),
      'myNullableGenderList': typeExample.myNullableGenderList
          ?.map((i4.Gender? listElement) => listElement?.name)
          .toList(),
      'myExampleList': typeExample.myExampleList
          .map((i1.TypeExample listElement) => i3.typeExampleToMap(listElement))
          .toList(),
      'myNullableExampleList': typeExample.myNullableExampleList
          ?.map((i1.TypeExample? listElement) =>
              listElement == null ? null : i3.typeExampleToMap(listElement))
          .toList()
    };
i1.TypeExample mapToTypeExample(Map<String, dynamic> typeExampleMap) =>
    i1.TypeExample()
      ..myString = typeExampleMap['myString'] as String
      ..myNullableString = typeExampleMap['myNullableString'] as String?
      ..myNum = typeExampleMap['myNum'] as num
      ..myNullableNum = typeExampleMap['myNullableNum'] as num?
      ..myInt = typeExampleMap['myInt'] as int
      ..myNullableInt = typeExampleMap['myNullableInt'] as int?
      ..myDouble = (typeExampleMap['myDouble'] as num).toDouble()
      ..myNullableDouble =
          (typeExampleMap['myNullableDouble'] as num?)?.toDouble()
      ..myBool = typeExampleMap['myBool'] as bool
      ..myNullableBool = typeExampleMap['myNullableBool'] as bool?
      ..myEnum = i4.Gender.values
          .firstWhere((enumValue) => enumValue.name == typeExampleMap['myEnum'])
      ..myNullableEnum = typeExampleMap['myNullableEnum'] == null
          ? null
          : i4.Gender.values.firstWhere(
              (enumValue) => enumValue.name == typeExampleMap['myNullableEnum'])
      ..myUri = Uri.parse(typeExampleMap['myUri'] as String)
      ..myNullableUri = typeExampleMap['myNullableUri'] == null
          ? null
          : Uri.parse(typeExampleMap['myNullableUri'] as String)
      ..myBigInt = BigInt.parse(typeExampleMap['myBigInt'] as String)
      ..myNullableBigInt = typeExampleMap['myNullableBigInt'] == null
          ? null
          : BigInt.parse(typeExampleMap['myNullableBigInt'] as String)
      ..myDateTime = DateTime.parse(typeExampleMap['myDateTime'] as String)
      ..myNullableDateTime = typeExampleMap['myNullableDateTime'] == null
          ? null
          : DateTime.parse(typeExampleMap['myNullableDateTime'] as String)
      ..myDuration = Duration(microseconds: typeExampleMap['myDuration'] as int)
      ..myNullableDuration = typeExampleMap['myNullableDuration'] == null
          ? null
          : Duration(microseconds: typeExampleMap['myNullableDuration'] as int)
      ..myPerson =
          i2.mapToPerson(typeExampleMap['myPerson'] as Map<String, dynamic>)
      ..myNullablePerson = typeExampleMap['myNullablePerson'] == null
          ? null
          : i2.mapToPerson(
              typeExampleMap['myNullablePerson'] as Map<String, dynamic>)
      ..myExample = i3
          .mapToTypeExample(typeExampleMap['myExample'] as Map<String, dynamic>)
      ..myNullableExample = typeExampleMap['myNullableExample'] == null
          ? null
          : i3.mapToTypeExample(
              typeExampleMap['myNullableExample'] as Map<String, dynamic>)
      ..myBoolList = typeExampleMap['myBoolList']
          .map((listElement) => listElement as bool)
          .toList()
      ..myNullableBoolList = typeExampleMap['myNullableBoolList']
          ?.map((listElement) => listElement as bool?)
          .toList()
      ..myNumList = typeExampleMap['myNumList']
          .map((listElement) => listElement as num)
          .toList()
      ..myNullableNumList = typeExampleMap['myNullableNumList']
          ?.map((listElement) => listElement as num?)
          .toList()
      ..myIntList = typeExampleMap['myIntList']
          .map((listElement) => listElement as int)
          .toList()
      ..myNullableIntList = typeExampleMap['myNullableIntList']
          ?.map((listElement) => listElement as int?)
          .toList()
      ..myDoubleList = typeExampleMap['myDoubleList']
          .map((listElement) => (listElement as num).toDouble())
          .toList()
      ..myNullableDoubleList = typeExampleMap['myNullableDoubleList']
          ?.map((listElement) => (listElement as num?)?.toDouble())
          .toList()
      ..myStringList = typeExampleMap['myStringList']
          .map((listElement) => listElement as String)
          .toList()
      ..myNullableStringList = typeExampleMap['myNullableStringList']
          ?.map((listElement) => listElement as String?)
          .toList()
      ..myUriList = typeExampleMap['myUriList']
          .map((listElement) => Uri.parse(listElement as String))
          .toList()
      ..myNullableUriList = typeExampleMap['myNullableUriList']
          ?.map((listElement) =>
              listElement == null ? null : Uri.parse(listElement as String))
          .toList()
      ..myBigIntList = typeExampleMap['myBigIntList']
          .map((listElement) => BigInt.parse(listElement as String))
          .toList()
      ..myNullableBigIntList = typeExampleMap['myNullableBigIntList']
          ?.map((listElement) =>
              listElement == null ? null : BigInt.parse(listElement as String))
          .toList()
      ..myDateTimeList = typeExampleMap['myDateTimeList']
          .map((listElement) => DateTime.parse(listElement as String))
          .toList()
      ..myNullableDateTimeList = typeExampleMap['myNullableDateTimeList']
          ?.map((listElement) => listElement == null
              ? null
              : DateTime.parse(listElement as String))
          .toList()
      ..myDurationList = typeExampleMap['myDurationList']
          .map((listElement) => Duration(microseconds: listElement as int))
          .toList()
      ..myNullableDurationList = typeExampleMap['myNullableDurationList']
          ?.map((listElement) => listElement == null
              ? null
              : Duration(microseconds: listElement as int))
          .toList()
      ..myGenderList = typeExampleMap['myGenderList']
          .map((listElement) => i4.Gender.values
              .firstWhere((enumValue) => enumValue.name == listElement))
          .toList()
      ..myNullableGenderList = typeExampleMap['myNullableGenderList']
          ?.map((listElement) => listElement == null
              ? null
              : i4.Gender.values
                  .firstWhere((enumValue) => enumValue.name == listElement))
          .toList()
      ..myExampleList = typeExampleMap['myExampleList']
          .map((listElement) =>
              i3.mapToTypeExample(listElement as Map<String, dynamic>))
          .toList()
      ..myNullableExampleList = typeExampleMap['myNullableExampleList']
          ?.map((listElement) => listElement == null
              ? null
              : i3.mapToTypeExample(listElement as Map<String, dynamic>))
          .toList();
