import '../../../example/lib/constructor/constructor.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/constructor/constructor.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class DefaultConstructorExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'DefaultConstructorExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName': 'DefaultConstructorExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const DefaultConstructorExampleMapper();
  i1.DefaultConstructorExample fromMap(
    Map<String, dynamic> defaultConstructorExampleMap,
  ) =>
      i1.DefaultConstructorExample()
        ..property1 = defaultConstructorExampleMap['property1'] as String
        ..property2 = defaultConstructorExampleMap['property2'] as String?;
  Map<String, dynamic> toMap(
    i1.DefaultConstructorExample defaultConstructorExample,
  ) =>
      {
        'property1': defaultConstructorExample.property1,
        'property2': defaultConstructorExample.property2,
      };
}

class ConstructorExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'ConstructorExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName': 'ConstructorExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ConstructorExampleMapper();
  i1.ConstructorExample fromMap(Map<String, dynamic> constructorExampleMap) =>
      i1.ConstructorExample()
        ..property1 = constructorExampleMap['property1'] as String
        ..property2 = constructorExampleMap['property2'] as String?;
  Map<String, dynamic> toMap(i1.ConstructorExample constructorExample) => {
        'property1': constructorExample.property1,
        'property2': constructorExample.property2,
      };
}

class ConstructorWithRequiredPositionalParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'ConstructorWithRequiredPositionalParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName':
        'ConstructorWithRequiredPositionalParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ConstructorWithRequiredPositionalParametersExampleMapper();
  i1.ConstructorWithRequiredPositionalParametersExample fromMap(
    Map<String, dynamic> constructorWithRequiredPositionalParametersExampleMap,
  ) =>
      i1.ConstructorWithRequiredPositionalParametersExample(
        constructorWithRequiredPositionalParametersExampleMap['property1']
            as String,
        constructorWithRequiredPositionalParametersExampleMap['property2']
            as String?,
      )
        ..property3 =
            constructorWithRequiredPositionalParametersExampleMap['property3']
                as String
        ..property4 =
            constructorWithRequiredPositionalParametersExampleMap['property4']
                as String?;
  Map<String, dynamic> toMap(
    i1.ConstructorWithRequiredPositionalParametersExample
        constructorWithRequiredPositionalParametersExample,
  ) =>
      {
        'property1':
            constructorWithRequiredPositionalParametersExample.property1,
        'property2':
            constructorWithRequiredPositionalParametersExample.property2,
        'property3':
            constructorWithRequiredPositionalParametersExample.property3,
        'property4':
            constructorWithRequiredPositionalParametersExample.property4,
      };
}

class ConstructorWithNamedParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'ConstructorWithNamedParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName': 'ConstructorWithNamedParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ConstructorWithNamedParametersExampleMapper();
  i1.ConstructorWithNamedParametersExample fromMap(
    Map<String, dynamic> constructorWithNamedParametersExampleMap,
  ) =>
      i1.ConstructorWithNamedParametersExample(
        property1:
            constructorWithNamedParametersExampleMap['property1'] as String,
        property2:
            constructorWithNamedParametersExampleMap['property2'] as String?,
      )
        ..property3 =
            constructorWithNamedParametersExampleMap['property3'] as String
        ..property4 =
            constructorWithNamedParametersExampleMap['property4'] as String?;
  Map<String, dynamic> toMap(
    i1.ConstructorWithNamedParametersExample
        constructorWithNamedParametersExample,
  ) =>
      {
        'property1': constructorWithNamedParametersExample.property1,
        'property2': constructorWithNamedParametersExample.property2,
        'property3': constructorWithNamedParametersExample.property3,
        'property4': constructorWithNamedParametersExample.property4,
      };
}

class ConstructorWithRequiredPositionalParametersAndNamedParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className':
        'ConstructorWithRequiredPositionalParametersAndNamedParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName':
        'ConstructorWithRequiredPositionalParametersAndNamedParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property5',
        'mapKey': 'property5',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property6',
        'mapKey': 'property6',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ConstructorWithRequiredPositionalParametersAndNamedParametersExampleMapper();
  i1.ConstructorWithRequiredPositionalParametersAndNamedParametersExample
      fromMap(
    Map<String, dynamic>
        constructorWithRequiredPositionalParametersAndNamedParametersExampleMap,
  ) =>
          i1
              .ConstructorWithRequiredPositionalParametersAndNamedParametersExample(
            constructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                'property1'] as String,
            constructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                'property2'] as String?,
            property3:
                constructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property3'] as String,
            property4:
                constructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property4'] as String?,
          )
            ..property5 =
                constructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property5'] as String
            ..property6 =
                constructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property6'] as String?;
  Map<String, dynamic> toMap(
    i1.ConstructorWithRequiredPositionalParametersAndNamedParametersExample
        constructorWithRequiredPositionalParametersAndNamedParametersExample,
  ) =>
      {
        'property1':
            constructorWithRequiredPositionalParametersAndNamedParametersExample
                .property1,
        'property2':
            constructorWithRequiredPositionalParametersAndNamedParametersExample
                .property2,
        'property3':
            constructorWithRequiredPositionalParametersAndNamedParametersExample
                .property3,
        'property4':
            constructorWithRequiredPositionalParametersAndNamedParametersExample
                .property4,
        'property5':
            constructorWithRequiredPositionalParametersAndNamedParametersExample
                .property5,
        'property6':
            constructorWithRequiredPositionalParametersAndNamedParametersExample
                .property6,
      };
}

class ConstructorWithOptionalParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'ConstructorWithOptionalParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName': 'ConstructorWithOptionalParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ConstructorWithOptionalParametersExampleMapper();
  i1.ConstructorWithOptionalParametersExample fromMap(
    Map<String, dynamic> constructorWithOptionalParametersExampleMap,
  ) =>
      i1.ConstructorWithOptionalParametersExample(
        constructorWithOptionalParametersExampleMap['property1'] as String,
        constructorWithOptionalParametersExampleMap['property2'] as String?,
      )
        ..property3 =
            constructorWithOptionalParametersExampleMap['property3'] as String
        ..property4 =
            constructorWithOptionalParametersExampleMap['property4'] as String?;
  Map<String, dynamic> toMap(
    i1.ConstructorWithOptionalParametersExample
        constructorWithOptionalParametersExample,
  ) =>
      {
        'property1': constructorWithOptionalParametersExample.property1,
        'property2': constructorWithOptionalParametersExample.property2,
        'property3': constructorWithOptionalParametersExample.property3,
        'property4': constructorWithOptionalParametersExample.property4,
      };
}

class ConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className':
        'ConstructorWithRequiredPositionalParametersAndOptionalParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName':
        'ConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property5',
        'mapKey': 'property5',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property6',
        'mapKey': 'property6',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMapper();
  i1.ConstructorWithRequiredPositionalParametersAndOptionalParametersExample
      fromMap(
    Map<String, dynamic>
        constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap,
  ) =>
          i1
              .ConstructorWithRequiredPositionalParametersAndOptionalParametersExample(
            constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property1'] as String,
            constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property2'] as String?,
            constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property3'] as String,
            constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property4'] as String?,
          )
            ..property5 =
                constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                    'property5'] as String
            ..property6 =
                constructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                    'property6'] as String?;
  Map<String, dynamic> toMap(
    i1.ConstructorWithRequiredPositionalParametersAndOptionalParametersExample
        constructorWithRequiredPositionalParametersAndOptionalParametersExample,
  ) =>
      {
        'property1':
            constructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property1,
        'property2':
            constructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property2,
        'property3':
            constructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property3,
        'property4':
            constructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property4,
        'property5':
            constructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property5,
        'property6':
            constructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property6,
      };
}

class NamedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className':
        'NamedConstructorWithRequiredPositionalParametersAndNamedParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName':
        'NamedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property5',
        'mapKey': 'property5',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property6',
        'mapKey': 'property6',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const NamedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMapper();
  i1.NamedConstructorWithRequiredPositionalParametersAndNamedParametersExample
      fromMap(
    Map<String, dynamic>
        namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap,
  ) =>
          i1.NamedConstructorWithRequiredPositionalParametersAndNamedParametersExample
              .name(
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                'property1'] as String,
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                'property2'] as String?,
            property3:
                namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property3'] as String,
            property4:
                namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property4'] as String?,
          )
            ..property5 =
                namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property5'] as String
            ..property6 =
                namedConstructorWithRequiredPositionalParametersAndNamedParametersExampleMap[
                    'property6'] as String?;
  Map<String, dynamic> toMap(
    i1.NamedConstructorWithRequiredPositionalParametersAndNamedParametersExample
        namedConstructorWithRequiredPositionalParametersAndNamedParametersExample,
  ) =>
      {
        'property1':
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExample
                .property1,
        'property2':
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExample
                .property2,
        'property3':
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExample
                .property3,
        'property4':
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExample
                .property4,
        'property5':
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExample
                .property5,
        'property6':
            namedConstructorWithRequiredPositionalParametersAndNamedParametersExample
                .property6,
      };
}

class NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMapper {
  static Map<String, dynamic> schema = {
    'className':
        'NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExample',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.dart',
    'mapperClassName':
        'NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/constructor/constructor.mapper.dart',
    'fields': [
      {
        'name': 'property1',
        'mapKey': 'property1',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property2',
        'mapKey': 'property2',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property3',
        'mapKey': 'property3',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property4',
        'mapKey': 'property4',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property5',
        'mapKey': 'property5',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'property6',
        'mapKey': 'property6',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMapper();
  i1.NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
      fromMap(
    Map<String, dynamic>
        namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap,
  ) =>
          i1.NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
              .name(
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property1'] as String,
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property2'] as String?,
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property3'] as String,
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                'property4'] as String?,
          )
            ..property5 =
                namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                    'property5'] as String
            ..property6 =
                namedConstructorWithRequiredPositionalParametersAndOptionalParametersExampleMap[
                    'property6'] as String?;
  Map<String, dynamic> toMap(
    i1.NamedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
        namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample,
  ) =>
      {
        'property1':
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property1,
        'property2':
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property2,
        'property3':
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property3,
        'property4':
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property4,
        'property5':
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property5,
        'property6':
            namedConstructorWithRequiredPositionalParametersAndOptionalParametersExample
                .property6,
      };
}
