import '../../../example/lib/remove_me/variable.domain.dart' as i1;
import '../../../example/lib/remove_me/variable.domain.mapper.dart' as i2;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/remove_me/variable.domain.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class BaseTypeMapper {
  static Map<String, dynamic> schema = {
    'className': 'BaseType',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/remove_me/variable.domain.dart',
    'mapperClassName': 'BaseTypeMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/remove_me/variable.domain.mapper.dart',
    'fields': [
      {
        'name': 'name',
        'mapKey': 'name',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const BaseTypeMapper();
  i1.BaseType fromMap(Map<String, dynamic> baseTypeMap) =>
      i1.BaseType()..name = baseTypeMap['name'] as String;
  Map<String, dynamic> toMap(i1.BaseType baseType) => {'name': baseType.name};
}

class VariableMapper {
  static Map<String, dynamic> schema = {
    'className': 'Variable',
    'classDescription': '',
    'classLibraryUri':
        'asset:map_converter/example/lib/remove_me/variable.domain.dart',
    'mapperClassName': 'VariableMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/remove_me/variable.domain.mapper.dart',
    'fields': [
      {
        'name': 'name',
        'mapKey': 'name',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'comment',
        'mapKey': 'comment',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'networkPublish',
        'mapKey': 'networkPublish',
        'description': '',
        'presence': 'required',
        'type': 'NetworkPublish',
        'typeLibraryUri':
            'asset:map_converter/example/lib/remove_me/variable.domain.dart',
      },
      {
        'name': 'baseType',
        'mapKey': 'baseType',
        'description': '',
        'presence': 'required',
        'type': 'BaseType',
        'typeLibraryUri':
            'asset:map_converter/example/lib/remove_me/variable.domain.dart',
      },
      {
        'name': 'hardwareAddress',
        'mapKey': 'hardwareAddress',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'direction',
        'mapKey': 'direction',
        'description': '',
        'presence': 'optional',
        'type': 'VariableDirection',
        'typeLibraryUri':
            'asset:map_converter/example/lib/remove_me/variable.domain.dart',
      },
      {
        'name': 'isRetained',
        'mapKey': 'isRetained',
        'description': '',
        'presence': 'required',
        'type': 'bool',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'isConstant',
        'mapKey': 'isConstant',
        'description': '',
        'presence': 'required',
        'type': 'bool',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'initialValue',
        'mapKey': 'initialValue',
        'description': '',
        'presence': 'optional',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const VariableMapper();
  i1.Variable fromMap(Map<String, dynamic> variableMap) => i1.Variable(
        name: variableMap['name'] as String,
        comment: variableMap['comment'] as String,
        networkPublish: i1.NetworkPublish.values.firstWhere(
          (enumValue) => enumValue.name == variableMap['networkPublish'],
        ),
        baseType: const i2.BaseTypeMapper().fromMap(
          variableMap['baseType'] as Map<String, dynamic>,
        ),
        hardwareAddress: variableMap['hardwareAddress'] as String?,
        direction: variableMap['direction'] == null
            ? null
            : i1.VariableDirection.values.firstWhere(
                (enumValue) => enumValue.name == variableMap['direction'],
              ),
        isRetained: variableMap['isRetained'] as bool,
        isConstant: variableMap['isConstant'] as bool,
        initialValue: variableMap['initialValue'] as String?,
      );
  Map<String, dynamic> toMap(i1.Variable variable) => {
        'name': variable.name,
        'comment': variable.comment,
        'networkPublish': variable.networkPublish.name,
        'baseType': const i2.BaseTypeMapper().toMap(variable.baseType),
        'hardwareAddress': variable.hardwareAddress,
        'direction': variable.direction?.name,
        'isRetained': variable.isRetained,
        'isConstant': variable.isConstant,
        'initialValue': variable.initialValue,
      };
}
