import 'dart:async';

import 'package:analyzer/dart/constant/value.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:build/build.dart';
import 'package:collection/collection.dart';
import 'package:dart_code/dart_code.dart' as code;
import 'package:logging/logging.dart';
import 'package:map_converter/map_converter.dart';
import 'package:map_converter/src/builder/value_expression_factory/value_expression_factory.dart';
import 'package:recase/recase.dart';

class MapConverterBuilder implements Builder {
  final BuilderOptions builderOptions;
  MapConverterBuilder(this.builderOptions);

  @override
  Future<FutureOr<void>> build(BuildStep buildStep) async {
    try {
      var idFactory = MapConverterLibraryAssetIdFactory(this);
      var libraryElement = await buildStep.inputLibrary;
      var library = MapperLibrary(idFactory, libraryElement);

      if (library.isNotEmpty) {
        AssetId outputId = idFactory.createOutputId(buildStep.inputId);
        var dartCode = library.toFormattedString();
        buildStep.writeAsString(outputId, dartCode);
        log.log(Level.INFO, 'Written: $outputId!');
      }
    } catch (e, stackTrace) {
      log.log(
          Level.SEVERE,
          'Error processing: ${buildStep.inputId.path}. Error: \n$e',
          stackTrace);
    }
  }

  @override
  Map<String, List<String>> get buildExtensions => {
        '^{{}}.dart': ['{{}}.mapper.dart']
      };
}

class MapConverterLibraryAssetIdFactory {
  final Builder builder;

  MapConverterLibraryAssetIdFactory(this.builder);

  /// [inputId] is the library file of the domain object(s).
  /// This will be converted to the library file that will
  /// contain the [MapConverter] for these domain object(s).
  AssetId createOutputId(AssetId inputId) {
    var assetIds = expectedOutputs(builder, inputId);
    var assetId = assetIds.first;
    return assetId;
  }

  String createOutputUriForType(InterfaceType domainObjectType) {
    var inputLibraryUri = domainObjectType.element.library.uri;
    var inputLibraryAssetId = AssetId.resolve(inputLibraryUri);
    var outputLibraryAssetId = createOutputId(inputLibraryAssetId);
    return outputLibraryAssetId.uri.toString();
  }
}

class MapperLibrary extends code.Library {
  MapperLibrary(MapConverterLibraryAssetIdFactory idFactory,
      LibraryElement libraryElement)
      : super(
          docComments: _createDocComments(libraryElement),
          classes: _createMapperClasses(libraryElement, idFactory),
        );

  bool get isNotEmpty => classes?.isNotEmpty ?? false;

  static List<code.Class> _createMapperClasses(LibraryElement libraryElement,
          MapConverterLibraryAssetIdFactory idFactory) =>
      DomainClassFactory()
          .create(libraryElement)
          .map((domainClass) => MapperClass(domainClass, idFactory))
          .toList();

  static List<code.DocComment> _createDocComments(
          LibraryElement libraryElement) =>
      [
        code.DocComment.fromList([
          'Do not make changes to this file!',
          'This file is generated by package: map_converter',
          'Input: ${libraryElement.uri.toString().replaceAll(RegExp(r'^asset:'), '')}',
          'Generate command: '
              'dart run build_runner build --delete-conflicting-outputs',
          'For more information see: https://pub.dev/packages/map_converter',
        ])
      ];
}

class MapperClass extends code.Class {
  MapperClass(
      DomainClass domainClass, MapConverterLibraryAssetIdFactory idFactory)
      : super(_name(domainClass), constructors: [
          _constructor(domainClass)
        ], methods: [
          FromMapValueMethod(domainClass, idFactory),
          ToMapValueMethod(domainClass, idFactory)
        ], fields: [
          SchemaField(domainClass, idFactory)
        ]);

  static String _name(DomainClass domainClass) =>
      '${domainClass.element.name!}Mapper';

  static code.Constructor _constructor(DomainClass domainClass) =>
      code.Constructor(code.Type(_name(domainClass)), constant: true);
}

class ToMapValueMethod extends code.Method {
  ToMapValueMethod(
    DomainClass domainClass,
    MapConverterLibraryAssetIdFactory idFactory,
  ) : super(
          'toMap',
          _createBody(domainClass, idFactory),
          parameters: _createParameters(domainClass),
          returnType: _createReturnType(),
        );

  static code.CodeNode _createBody(
    DomainClass domainClass,
    MapConverterLibraryAssetIdFactory idFactory,
  ) {
    Map<code.Expression, code.Expression> map = {};
    for (var field in domainClass.fields.where((f) =>
        f.element.name != null && f.toMapValueExpressionFunction != null)) {
      var fieldName =
          code.Expression.ofString(field.alias ?? field.element.name!);
      var fieldType = field.element.type as InterfaceType;
      var instanceVariableName = domainClass.element.name!.camelCase;
      var source = code.Expression.ofVariable(instanceVariableName)
          .getProperty(field.element.name!);
      var fieldValueExpression = field.toMapValueExpressionFunction!(
        idFactory,
        source,
        fieldType,
      );
      map[fieldName] = fieldValueExpression;
    }
    return code.Expression.ofMap(map);
  }

  static code.Parameters _createParameters(DomainClass domainClass) =>
      code.Parameters([
        code.Parameter.required(
          domainClass.element.name!.camelCase,
          type: createDomainType(domainClass),
        ),
      ]);

  static code.Type _createReturnType() => code.Type.ofMap(
      keyType: code.Type.ofString(), valueType: code.Type.ofDynamic());
}

class FromMapValueMethod extends code.Method {
  FromMapValueMethod(
    DomainClass domainClass,
    MapConverterLibraryAssetIdFactory idFactory,
  ) : super(
          'fromMap',
          _createBody(domainClass, idFactory),
          parameters: _createFunctionParameters(domainClass),
          returnType: createDomainType(domainClass),
        );

  static code.CodeNode _createBody(
    DomainClass domainClass,
    MapConverterLibraryAssetIdFactory idFactory,
  ) {
    var domainMapVariableName = _domainMapVariableName(domainClass);
    var constructorCall = _createConstructorCall(
      domainClass,
      idFactory,
    );
    for (var field in domainClass.fieldsSetBySetter) {
      var propertyName = field.alias ?? field.element.name!;
      var propertyValue = propertyValueExpression(
        field,
        idFactory,
        domainMapVariableName,
      );
      constructorCall = constructorCall.setProperty(
        propertyName,
        propertyValue,
        cascade: true,
      );
    }
    return constructorCall;
  }

  static code.Expression _createConstructorCall(
      DomainClass domainClass, MapConverterLibraryAssetIdFactory idFactory) {
    var name = domainClass.bestConstructor.name;
    if (name == 'new') {
      name = null;
    }
    var parameters = _createConstructorParameterValues(domainClass, idFactory);
    return code.Expression.callConstructor(createDomainType(domainClass),
        name: name, parameterValues: parameters);
  }

  static code.Parameters _createFunctionParameters(DomainClass domainClass) =>
      code.Parameters([
        code.Parameter.required(
          _domainMapVariableName(domainClass),
          type: code.Type.ofMap(
              keyType: code.Type.ofString(), valueType: code.Type.ofDynamic()),
        ),
      ]);

  static String _domainMapVariableName(DomainClass domainClass) =>
      '${domainClass.element.name!.camelCase}Map';

  static code.ParameterValues _createConstructorParameterValues(
    DomainClass domainClass,
    MapConverterLibraryAssetIdFactory idFactory,
  ) {
    var bestConstructor = domainClass.bestConstructor;
    String mapVariableName = _domainMapVariableName(domainClass);
    var parameterValues = <code.ParameterValue>[];
    for (var parameter in bestConstructor.requiredPositionalParameters) {
      code.Expression valueExpression =
          propertyValueExpression(parameter, idFactory, mapVariableName);
      parameterValues.add(code.ParameterValue(valueExpression));
    }
    for (var parameter in bestConstructor.optionalParameters) {
      code.Expression valueExpression =
          propertyValueExpression(parameter, idFactory, mapVariableName);
      parameterValues.add(code.ParameterValue(valueExpression));
    }
    for (var parameter in bestConstructor.namedParameters) {
      code.Expression valueExpression =
          propertyValueExpression(parameter, idFactory, mapVariableName);
      parameterValues.add(
          code.ParameterValue.named(parameter.element.name!, valueExpression));
    }
    return code.ParameterValues(parameterValues);
  }
}

code.Type createDomainType(DomainClass domainClass) => code.Type(
      domainClass.element.name!,
      libraryUri: createLibraryUri(domainClass.element),
    );

code.Expression propertyValueExpression(FieldMetadata field,
    MapConverterLibraryAssetIdFactory idFactory, String mapVariableName) {
  var fieldName = field.alias ?? field.element.name!;
  var fieldType = field.element.type as InterfaceType;
  var source = code.Expression.ofVariable(mapVariableName)
      .index(code.Expression.ofString(fieldName));
  var valueExpression = field.fromMapValueExpressionFunction!(
    idFactory,
    source,
    fieldType,
  );
  return valueExpression;
}

/// Contains information on a [DomainClass] to generate [MapConverter]s
class DomainClass {
  final ClassElement element;
  final Constructor bestConstructor;
  final List<FieldMetadata> fields;
  final List<FieldMetadata> fieldsSetBySetter;

  DomainClass(
    this.element,
    this.bestConstructor,
    this.fields,
  ) : fieldsSetBySetter = fields
            .where((field) =>
                !bestConstructor.fieldsBeingSet.contains(field) &&
                field.element.setter != null)
            .toList();
}

class Constructor {
  late String? name;
  final List<FieldMetadata> requiredPositionalParameters;
  final List<FieldMetadata> namedParameters;
  final List<FieldMetadata> optionalParameters;
  late Set<FieldMetadata> fieldsBeingSet;

  Constructor({
    String? name,
    required this.requiredPositionalParameters,
    required this.namedParameters,
    required this.optionalParameters,
  }) {
    this.name = (name == null || name.isEmpty) ? null : name;
    fieldsBeingSet = {};
    fieldsBeingSet.addAll(requiredPositionalParameters);
    fieldsBeingSet.addAll(namedParameters);
    fieldsBeingSet.addAll(optionalParameters);
  }

  Constructor.withoutParameters()
      : name = null,
        requiredPositionalParameters = [],
        namedParameters = [],
        optionalParameters = [],
        fieldsBeingSet = {};
}

class FieldMetadata {
  final FieldElement element;
  final String? alias;
  final ToMapValueExpressionFunction? toMapValueExpressionFunction;
  final FromMapValueExpressionFunction? fromMapValueExpressionFunction;

  FieldMetadata(this.element,
      {this.alias,
      required this.toMapValueExpressionFunction,
      required this.fromMapValueExpressionFunction});
}

typedef ToMapValueExpressionFunction =

    /// Creates a Dart code expressions for a generated MapConverter
    /// to convert a [source] object to a [PrimitiveType]
    code.Expression Function(
  MapConverterLibraryAssetIdFactory idFactory,

  /// [source]: An expression of the source data, e.g.:
  /// * person.name (a field or property value of an object)
  /// * enumValue
  /// * listElement
  /// * setElement
  /// * k (for a key value in a [Map])
  /// * v (for a value in a [Map])
  code.Expression source,
  InterfaceType typeToConvert,
);

typedef FromMapValueExpressionFunction =

    /// Creates a Dart code expressions for a generated MapConverter
    /// to convert a [PrimitiveType] to an object
    code.Expression Function(
  MapConverterLibraryAssetIdFactory idFactory,

  /// [source]: An expression of the source data, e.g.:
  /// * personMap['propertyName'] (a [PrimitiveType] within a [Map])
  /// * enumValue
  /// * listElement
  /// * setElement
  /// * k (for a key value in a [Map])
  /// * v (for a value in a [Map])
  code.Expression source,
  InterfaceType typeToConvert,
);

class DomainClassFactory {
  List<DomainClass> create(LibraryElement libraryElement) {
    var domainClasses = <DomainClass>[];
    var topElements = libraryElement.children;
    for (var topElement in topElements) {
      if (isDomainClass(topElement)) {
        var classElement = topElement as ClassElement;
        var fields = _createFields(classElement);
        if (fields.isNotEmpty) {
          var bestConstructor =
              BestConstructorFactory().createFor(classElement, fields);
          var fieldsThatAreNotSet =
              findFieldsThatAreNotSet(fields, bestConstructor);
          validateIfAllFieldsAreSet(fieldsThatAreNotSet, classElement);
          if (fieldsThatAreNotSet.length != fields.length) {
            var domainClass =
                DomainClass(classElement, bestConstructor, fields);
            domainClasses.add(domainClass);
          }
        }
      }
    }
    return domainClasses;
  }

  void validateIfAllFieldsAreSet(
      List<FieldMetadata> fieldsThatAreNotSet, ClassElement classElement) {
    if (fieldsThatAreNotSet.isNotEmpty) {
      var fieldNamesThatAreNotSet =
          fieldsThatAreNotSet.map((field) => field.element.name).join(', ');
      log.log(
          Level.WARNING,
          'Class: ${classElement.name} '
          'contains fields that could not be set: $fieldNamesThatAreNotSet');
    }
  }

  bool isDomainClass(Element element) {
    return _hasMapConverterAnnotation(element) &&
        element is ClassElement &&
        element.isPublic &&
        !element.isAbstract &&
        element is! EnumElement &&
        element.thisType.allSupertypes
            .none((e) => _isListSetMapIteratorType(e.element));
  }

  bool isDomainClassWithSupportedPropertyTypes(Element element) {
    return isDomainClass(element) &&
        _createFields(element as ClassElement).isNotEmpty;
  }

  bool _isListSetMapIteratorType(InterfaceElement element) {
    String string = element.toString();
    return element.library.name == 'dart.core' &&
        (string.contains('class List<') ||
            string.contains('class Set<') ||
            string.contains('class Map<') ||
            string.contains('class Iterator<'));
  }

  /// Gets all fields that represent properties from the [InterfaceElement]
  /// including those from super classes, mixins and interfaces
  List<FieldElement> _findAllPublicFields(InterfaceElement interfaceElement) {
    Map<String, FieldElement> fields = {};
    for (var element in interfaceElement.fields) {
      if (_isPublicPropertyField(element)) {
        fields[element.name!] = element;
      }
    }
    for (var superType in interfaceElement.allSupertypes) {
      var superTypeFields = _findAllPublicFields(superType.element);
      for (var superTypeField in superTypeFields) {
        fields[superTypeField.name!] = superTypeField;
      }
    }
    return fields.values.toList();
  }

  List<FieldMetadata> _createFields(ClassElement classElement) {
    final mapConverterAnnotation = findMapConverterAnnotation(classElement);

    var fieldMetaData = <FieldMetadata>[];
    var fields = _findAllPublicFields(classElement);
    var fieldAnnotations = _findFieldAnnotations(mapConverterAnnotation);
    for (var field in fields) {
      var fieldAnnotation = findFieldAnnotation(fieldAnnotations, field);
      var ignore = fieldAnnotation?.getField('ignore')?.toBoolValue() ?? false;
      if (!ignore) {
        var fieldPath = '${classElement.name}.${field.name}';
        try {
          var fieldType = field.type as InterfaceType;
          var valueExpressionFactory =
              ValueExpressionFactories().findFor(fieldType);
          var alias = fieldAnnotation?.getField('alias')?.toStringValue();
          var fromMapValueExpressionFunction =
              createFromMapValueExpressionFunction(
                  fieldAnnotation, valueExpressionFactory);
          var toMapValueExpressionFunction = createToMapValueExpressionFunction(
              fieldAnnotation, valueExpressionFactory);

          if (fromMapValueExpressionFunction == null &&
              toMapValueExpressionFunction == null) {
            log.log(
                Level.WARNING,
                'Property: $fieldPath '
                'has an unsupported type: $fieldType. '
                'Define a custom converter in the @MapConverter annotation.');
          } else {
            var fieldExpressionFactory = FieldMetadata(
              field,
              alias: alias,
              fromMapValueExpressionFunction: fromMapValueExpressionFunction,
              toMapValueExpressionFunction: toMapValueExpressionFunction,
            );
            fieldMetaData.add(fieldExpressionFactory);
          }
        } on Exception catch (e) {
          throw Exception('$fieldPath: $e');
        }
      }
    }
    return fieldMetaData;
  }

  DartObject? findFieldAnnotation(
      List<DartObject>? fieldAnnotations, FieldElement field) {
    return fieldAnnotations?.firstWhereOrNull((dartObject) =>
        (dartObject.getField('symbol')?.toSymbolValue()) == field.name);
  }

  FromMapValueExpressionFunction? createFromMapValueExpressionFunction(
      DartObject? fieldAnnotation,
      ValueExpressionFactory? valueExpressionFactory) {
    var fromMapValueCustomFunction =
        fieldAnnotation?.getField('fromMapValue')?.toFunctionValue();
    if (fromMapValueCustomFunction == null && valueExpressionFactory == null) {
      return null;
    }
    if (fromMapValueCustomFunction != null) {
      return createCustomFromMapValueExpressionFunction(
          functionName: fromMapValueCustomFunction.name!,
          functionLibraryUri: createRelativeLibraryUri(
              fromMapValueCustomFunction.library.uri.toString()));
    } else {
      return valueExpressionFactory!.fromMapValue;
    }
  }

  ToMapValueExpressionFunction? createToMapValueExpressionFunction(
      DartObject? fieldAnnotation,
      ValueExpressionFactory? valueExpressionFactory) {
    var toMapValueExpressionFunction =
        fieldAnnotation?.getField('toMapValue')?.toFunctionValue();
    if (toMapValueExpressionFunction == null &&
        valueExpressionFactory == null) {
      return null;
    }
    if (toMapValueExpressionFunction != null) {
      return createCustomToMapValueExpressionFunction(
          functionName: toMapValueExpressionFunction.name!,
          functionLibraryUri: createRelativeLibraryUri(
              toMapValueExpressionFunction.library.uri.toString()));
    } else {
      return valueExpressionFactory!.toMapValue;
    }
  }

  List<DartObject>? _findFieldAnnotations(DartObject? mapConverterAnnotation) =>
      mapConverterAnnotation?.getField('fields')?.toListValue();

  bool _isPublicPropertyField(FieldElement element) =>
      element.isPublic &&
      !element.isAbstract &&
      !element.isStatic &&
      !element.isConst &&
      (element.setter != null || _isSetInConstructor(element)) &&
      element.type is InterfaceType;

  bool _isSetInConstructor(FieldElement element) => element.isFinal;

  bool _hasMapConverterAnnotation(Element element) {
    for (var annotation in element.metadata.annotations) {
      var constantValue = annotation.computeConstantValue();
      if (constantValue?.type?.element?.name == "MapConverter") {
        return true;
      }
    }
    return false;
  }

  List<FieldMetadata> findFieldsThatAreNotSet(
      List<FieldMetadata> fields, Constructor bestConstructor) {
    var fieldsSetByConstructor = bestConstructor.fieldsBeingSet;
    var fieldsWithSetter =
        fields.where((field) => field.element.setter != null);
    var fieldsThatAreNotSet = [...fields]..removeWhere((field) =>
        fieldsSetByConstructor.contains(field) ||
        fieldsWithSetter.contains(field));
    return fieldsThatAreNotSet;
  }
}

FromMapValueExpressionFunction createCustomFromMapValueExpressionFunction({
  required String functionName,
  required String functionLibraryUri,
}) =>
    (
      MapConverterLibraryAssetIdFactory idFactory,
      code.Expression source,
      InterfaceType typeToConvert,
    ) =>
        code.Expression.callMethodOrFunction(
          functionName,
          libraryUri: functionLibraryUri,
          parameterValues: code.ParameterValues([code.ParameterValue(source)]),
        );

ToMapValueExpressionFunction createCustomToMapValueExpressionFunction({
  required String functionName,
  required String functionLibraryUri,
}) =>
    (
      MapConverterLibraryAssetIdFactory idFactory,
      code.Expression source,
      InterfaceType typeToConvert,
    ) =>
        code.Expression.callMethodOrFunction(
          functionName,
          libraryUri: functionLibraryUri,
          parameterValues: code.ParameterValues([code.ParameterValue(source)]),
        );

class BestConstructorFactory {
  /// returns the best constructor to be used to create an DomainObject when
  /// converting a [Map] to a DomainObject
  Constructor createFor(ClassElement classElement, List<FieldMetadata> fields) {
    var constructors = _usefulConstructors(classElement, fields);
    _orderByNumberOfPropertiesSet(constructors);
    return constructors.first;
  }

  /// constructor that sets most properties is put at the begin of the list
  void _orderByNumberOfPropertiesSet(List<Constructor> constructors) =>
      constructors.sort(
          (a, b) => b.fieldsBeingSet.length.compareTo(a.fieldsBeingSet.length));

  List<Constructor> _usefulConstructors(
    ClassElement classElement,
    List<FieldMetadata> fields,
  ) {
    var constructors = <Constructor>[];
    for (var constructorElement in classElement.constructors) {
      Constructor? constructor = _usefulConstructor(constructorElement, fields);
      if (constructor != null) {
        constructors.add(constructor);
      }
    }
    if (constructors.isEmpty) {
      constructors.add(Constructor.withoutParameters());
    }
    return constructors;
  }

  /// returns null if the constructor has parameters that can not be mapped to fields
  Constructor? _usefulConstructor(
      ConstructorElement constructorElement, List<FieldMetadata> fields) {
    var name = constructorElement.name;
    var requiredPositionalParameters = <FieldMetadata>[];
    var namedParameters = <FieldMetadata>[];
    var optionalParameters = <FieldMetadata>[];
    for (var parameter in constructorElement.formalParameters) {
      var field = _findProperty(parameter, fields);
      if (field == null && parameter.isRequired) {
        //do not know what to do with this constructor parameter
        return null;
      }
      if (field != null) {
        if (parameter.isRequiredPositional) {
          requiredPositionalParameters.add(field);
        } else if (parameter.isNamed) {
          namedParameters.add(field);
        } else if (parameter.isOptional) {
          optionalParameters.add(field);
        }
      }
    }
    return Constructor(
      name: name,
      requiredPositionalParameters: requiredPositionalParameters,
      namedParameters: namedParameters,
      optionalParameters: optionalParameters,
    );
  }

  FieldMetadata? _findProperty(
    FormalParameterElement parameter,
    List<FieldMetadata> fields,
  ) =>
      fields.firstWhereOrNull((field) => _isComparable(parameter, field));

  bool _isComparable(FormalParameterElement parameter, FieldMetadata field) =>
      field.element.name == parameter.name &&
      field.element.type.element != null &&
      parameter.type.element != null &&
      field.element.type.element!.name == parameter.type.element!.name &&
      field.element.type.element?.library?.uri ==
          parameter.type.element?.library?.uri;
}

// e.g.:
// {
//     'className': 'Example',
//     'classDescription': '',
//     'classLibraryUri': 'asset:map_converter/example/lib/alias/alias.dart',
//     'mapperClassName': 'ExampleMapper',
//     'mapperClassLibraryUri':
//         'asset:map_converter/example/lib/alias/alias.mapper.dart',
//     'fields': [
//       {
//         'name': 'email',
//         'mapKey': 'emailAddress',
//         'description': '',
//         'presence': 'required',
//         'type': 'String',
//         'typeLibraryUri': 'dart:core',
//       }]}
class SchemaField extends code.Field {
  SchemaField(
      DomainClass domainClass, MapConverterLibraryAssetIdFactory idFactory)
      : super('schema',
            type: _type(),
            static: true,
            value: _toMapExpression(domainClass, idFactory));

  static code.Type _type() {
    return code.Type.ofMap(
        keyType: code.Type.ofString(), valueType: code.Type.ofDynamic());
  }

  static code.Expression _toMapExpression(DomainClass domainClass,
          MapConverterLibraryAssetIdFactory idFactory) =>
      code.Expression.ofMap({
        code.Expression.ofString('className'):
            code.Expression.ofString(domainClass.element.name!),
        code.Expression.ofString('classDescription'): code.Expression.ofString(
            domainClass.element.documentationComment ?? ''),
        code.Expression.ofString('classLibraryUri'): code.Expression.ofString(
            domainClass.element.library.uri.toString()),
        code.Expression.ofString('mapperClassName'):
            code.Expression.ofString('${domainClass.element.name}Mapper'),
        code.Expression.ofString('mapperClassLibraryUri'):
            code.Expression.ofString(
                idFactory.createOutputUriForType(domainClass.element.thisType)),
        code.Expression.ofString('fields'):
            _toFieldsExpression(domainClass.fields)
      });

  static code.Expression _toFieldsExpression(List<FieldMetadata> fields) =>
      code.Expression.ofList(fields.map(_toFieldMapExpression).toList());

  static code.Expression _toFieldMapExpression(FieldMetadata field) =>
      code.Expression.ofMap({
        code.Expression.ofString('name'):
            code.Expression.ofString(field.element.name!),
        code.Expression.ofString('mapKey'):
            code.Expression.ofString(field.alias ?? field.element.name!),
        code.Expression.ofString('description'):
            code.Expression.ofString(field.element.documentationComment ?? ''),
        code.Expression.ofString('presence'): code.Expression.ofString(
            field.element.type.nullabilitySuffix == NullabilitySuffix.question
                ? 'optional'
                : 'required'),
        code.Expression.ofString('type'):
            code.Expression.ofString(field.element.type.element?.name ?? ''),
        code.Expression.ofString('typeLibraryUri'): code.Expression.ofString(
            field.element.type.element?.library?.uri.toString() ?? ''),
      });
}
