import 'package:map_converter/domain/person/person.dart' as _i1;

/// Do not make changes to this file!
/// This file is generated by: MapConverterBuilder
/// On: 2022-08-23 21:08:16.759526
/// From: /map_converter/lib/domain/person/person.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
Map<String, dynamic> personToMap(_i1.Person person) => {
      'name': person.name,
      'dateOfBirth': person.dateOfBirth.toIso8601String(),
      'hobby': person.hobby,
      'gender': person.gender.name
    };

_i1.Person mapToPerson(Map<String, dynamic> personMap) => _i1.Person()
  ..name = personMap['name'] as String
  ..dateOfBirth = DateTime.parse(personMap['dateOfBirth'] as String)
  ..hobby = personMap['hobby'] as String
  ..gender = _i1.Gender.values.firstWhere((e) => e.name == personMap['gender']);
