import '../../../example/lib/ignore/ignore.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/ignore/ignore.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/ignore/ignore.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/ignore/ignore.mapper.dart',
    'fields': [
      {
        'name': 'keep',
        'mapKey': 'keep',
        'description': '',
        'presence': 'required',
        'type': 'bool',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) =>
      i1.Example()..keep = exampleMap['keep'] as bool;
  Map<String, dynamic> toMap(i1.Example example) => {'keep': example.keep};
}
