import '../../../example/lib/custom/custom.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/custom/custom.dart
/// Generate command: dart run build_runner build
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  final Map<String, dynamic> schema = const {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/custom/custom.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/custom/custom.mapper.dart',
    'fields': [
      {
        'name': 'dateTime',
        'mapKey': 'dateTime',
        'description': '',
        'presence': 'required',
        'type': 'DateTime',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) =>
      i1.Example(i1.dateTimeFromMapValue(exampleMap['dateTime']));
  Map<String, dynamic> toMap(i1.Example example) => {
        'dateTime': i1.dateTimeToMapValue(example.dateTime),
      };
}
