import '../../../example/lib/person/person.dart' as i1;
import '../../../example/lib/person/person_map_converter.dart' as i2;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/person/person.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class PersonMapper {
  const PersonMapper();
  i1.Person fromMap(Map<String, dynamic> personMap) => i1.Person(
        personMap['name'] as String,
        dateOfBirth: DateTime.parse(personMap['dateOfBirth'] as String),
        hobby: personMap['hobby'] as String,
        gender: i1.Gender.values.firstWhere(
          (enumValue) => enumValue.name == personMap['gender'],
        ),
        children: personMap['children']
            .map(
              (listElement) => const i2.PersonMapper().fromMap(
                listElement as Map<String, dynamic>,
              ),
            )
            .toList()
            .cast<i1.Person>(),
      );
  Map<String, dynamic> toMap(i1.Person person) => {
        'name': person.name,
        'dateOfBirth': person.dateOfBirth.toIso8601String(),
        'children': person.children
            .map(
              (i1.Person listElement) =>
                  const i2.PersonMapper().toMap(listElement),
            )
            .toList(),
        'hobby': person.hobby,
        'gender': person.gender.name,
      };
}
