import '../../../example/lib/alias/alias.dart' as i1;

/// Do not make changes to this file!
/// This file is generated by package: map_converter
/// Input: map_converter/example/lib/alias/alias.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: https://pub.dev/packages/map_converter
class ExampleMapper {
  static Map<String, dynamic> schema = {
    'className': 'Example',
    'classDescription': '',
    'classLibraryUri': 'asset:map_converter/example/lib/alias/alias.dart',
    'mapperClassName': 'ExampleMapper',
    'mapperClassLibraryUri':
        'asset:map_converter/example/lib/alias/alias.mapper.dart',
    'fields': [
      {
        'name': 'email',
        'mapKey': 'emailAddress',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'phoneNumber',
        'mapKey': 'contactNumber',
        'description': '',
        'presence': 'required',
        'type': 'int',
        'typeLibraryUri': 'dart:core',
      },
      {
        'name': 'name',
        'mapKey': 'name',
        'description': '',
        'presence': 'required',
        'type': 'String',
        'typeLibraryUri': 'dart:core',
      },
    ],
  };
  const ExampleMapper();
  i1.Example fromMap(Map<String, dynamic> exampleMap) => i1.Example(
        name: exampleMap['name'] as String,
        email: exampleMap['emailAddress'] as String,
        phoneNumber: (exampleMap['contactNumber'] as num).toInt(),
      );
  Map<String, dynamic> toMap(i1.Example example) => {
        'emailAddress': example.email,
        'contactNumber': example.phoneNumber,
        'name': example.name,
      };
}
